[project]
name = "neurips-3dgs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.0",
    "lancedb>=0.27.1",
    "pandas>=3.0.0",
    "sentence-transformers>=5.2.2",
    "uvicorn>=0.40.0",
]
